openapi: 3.0.3
info:
  title: Orbis OpenAPI
  version: 0.1.0
  description: API specification for Orbis
servers:
  - url: http://localhost:3000
    description: Local dev
paths:
  /health:
    get:
      summary: Health check
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
components:
  schemas:
    Health:
      type: object
      properties:
        status:
          type: string
          example: ok
        uptime:
          type: number
          format: float
          example: 123.45
      required:
        - status
        - uptime
